import { PatternGene } from './types';

const basePatterns: PatternGene[] = [
  {
    id: '1',
    heCode: 'HE-N-B-R01',
    name: {
      'zh-CN': '凤穿牡丹',
      'zh-TW': '鳳穿牡丹',
      en: 'Phoenix Peony',
      ja: '鳳凰と牡丹',
      ko: '봉황과 모란',
    },
    imageUrl: 'https://api.dicebear.com/9.x/shapes/svg?seed=PhoenixPeony&backgroundColor=transparent',
    categoryLabels: [],
    era: '清代 (Qing Dynasty)',
    carrier: '服饰 (Clothing)',
    region: '湖北武汉 (Wuhan, Hubei)',
    copyrightOwner: '湖北省博物馆 (Hubei Provincial Museum)',
    format: 'PNG (Alpha)',
    resolution: '4K',
    craft: { 'zh-CN': '平绣、盘金绣', en: 'Flat Embroidery, Gold Couching' },
    symbolism: { 'zh-CN': '吉祥富贵', en: 'Auspicious Wealth' },
    origin: { 'zh-CN': '民间采集', en: 'Folk Collection' },
    scenario: { 'zh-CN': '婚庆礼服', en: 'Wedding Dress' },
    literature: { 'zh-CN': '《汉口竹枝词》', en: 'Hankou Bamboo Branch Poems' },
    inheritor: { 'zh-CN': '黄春萍', en: 'Huang Chunping' },
    createdAt: '2024-01-01T00:00:00Z',
    views: 1205,
  },
  {
    id: '2',
    heCode: 'HE-N-L-B02',
    name: {
      'zh-CN': '蝶恋花',
      'zh-TW': '蝶戀花',
      en: 'Butterfly and Flower',
      ja: '蝶と花',
      ko: '나비와 꽃',
    },
    imageUrl: 'https://api.dicebear.com/9.x/shapes/svg?seed=ButterflyFlower&backgroundColor=transparent',
    categoryLabels: [],
    era: '民国 (Republic of China)',
    carrier: '荷包 (Pouch)',
    region: '湖北荆州 (Jingzhou, Hubei)',
    copyrightOwner: '民间收藏 (Private Collection)',
    format: 'PNG (Alpha)',
    resolution: '8K',
    craft: { 'zh-CN': '打籽绣', en: 'Seed Stitch' },
    symbolism: { 'zh-CN': '爱情美满', en: 'Happy Love' },
    origin: { 'zh-CN': '古玩市场征集', en: 'Antique Market Collection' },
    scenario: { 'zh-CN': '日常佩戴', en: 'Daily Wear' },
    literature: { 'zh-CN': '无', en: 'None' },
    inheritor: { 'zh-CN': '佚名', en: 'Anonymous' },
    createdAt: '2024-01-02T00:00:00Z',
    views: 890,
  },
  {
    id: '3',
    heCode: 'HE-G-S-A01',
    name: {
      'zh-CN': '万字不断头',
      'zh-TW': '萬字不斷頭',
      en: 'Endless Wan Pattern',
      ja: '万字つなぎ',
      ko: '만자 연속문',
    },
    imageUrl: 'https://api.dicebear.com/9.x/shapes/svg?seed=Endless&backgroundColor=transparent',
    categoryLabels: [],
    era: '清代 (Qing Dynasty)',
    carrier: '挂屏 (Hanging Screen)',
    region: '湖北汉口 (Hankou, Hubei)',
    copyrightOwner: '公共领域 (Public Domain)',
    format: 'PNG (Alpha)',
    resolution: '12K',
    craft: { 'zh-CN': '挑花', en: 'Cross Stitch' },
    symbolism: { 'zh-CN': '绵长不断', en: 'Endless Longevity' },
    origin: { 'zh-CN': '传世藏品', en: 'Handed Down' },
    scenario: { 'zh-CN': '家居装饰', en: 'Home Decor' },
    literature: { 'zh-CN': '《绣谱》', en: 'Embroidery Manual' },
    inheritor: { 'zh-CN': '群体传承', en: 'Community' },
    createdAt: '2024-01-03T00:00:00Z',
    views: 2450,
  },
];

const names = [
  '莲生贵子',
  '鱼戏莲叶',
  '祥云如意',
  '石榴多子',
  '喜上眉梢',
  '团花锦簇',
  '牡丹团寿',
  '瑞草云纹',
  '蝙蝠捧寿',
  '缠枝莲纹',
  '双蝶迎春',
  '梅兰竹菊',
  '龙凤呈祥',
  '瓜瓞绵绵',
  '海水江崖',
  '八宝吉纹',
  '连珠团花',
  '荷塘清趣',
  '瑞鸟衔花',
  '福寿双全',
  '锦地花卉',
  '花篮献瑞',
  '万福流云',
  '金线团牡丹',
];

export const mockPatterns: PatternGene[] = [...basePatterns];

for (let i = 4; i <= 27; i += 1) {
  const source = basePatterns[i % basePatterns.length];
  const name = names[i - 4];

  mockPatterns.push({
    ...source,
    id: i.toString(),
    heCode: `HE-${['N', 'H', 'G'][i % 3]}-${['B', 'S', 'L'][i % 3]}-${['R', 'G', 'B', 'A', 'M'][i % 5]}${i.toString().padStart(2, '0')}`,
    name: {
      'zh-CN': name,
      'zh-TW': name,
      en: `Han Embroidery Pattern ${i}`,
      ja: `漢繍文様 ${i}`,
      ko: `한수 문양 ${i}`,
    },
    imageUrl: `https://api.dicebear.com/9.x/shapes/svg?seed=HanxiuPattern${i}&backgroundColor=transparent`,
    views: source.views + i * 37,
  });
}
